name: build

on:
  push:
    branches: [ "master", "develop" ]
    tags:
    - 'v*'
  pull_request:
    branches: [ "master", "develop" ]

env:
  BUILD_TYPE: Release
  FLASHER_BIN: FLASHER.BIN
  LAUNCHER_BIN: LAUNCHER.BIN
  BASICROM_BIN: BASICBOOTSTRAP.BIN
  MULTIROM_BIN: MULTIROM.BIN

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

################################################################################

  # Launcher for the SLOT2 cartridge
  build-launcher:
    runs-on: ubuntu-latest
    container: 
      image: z88dk/z88dk

    steps:
    - uses: actions/checkout@v3
    - name: Build launcher application
      run: |
        cd src
        sed -i 's/node[[:digit:]]\+/node2000000/g' Makefile
        make launcher
        ls -alh LAUNCHER*
    - name: Upload launcher
      uses: actions/upload-artifact@v4
      with:
        name: LAUNCHER-UNSIGNED
        path: src/${{env.LAUNCHER_BIN}}

  sign-launcher:
    runs-on: ubuntu-latest
    needs: [build-launcher]
    permissions: write-all
    steps:
    - name: Install dependencies
      run: sudo apt install -y cmake build-essential libtclap-dev libboost-all-dev git
    - name: Download repository
      run: git clone https://github.com/ifilot/crc16sign.git --depth 1
    - name: build crc16sign
      run: |
        cd crc16sign
        mkdir build
        cd build
        cmake ../src
        make -j
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: LAUNCHER-UNSIGNED
        path: ./
    - name: Sign binary
      run: |
        crc16sign/build/crc16sign -i ${{env.LAUNCHER_BIN}} -o ${{env.LAUNCHER_BIN}} -s
    - name: Upload launcher
      uses: actions/upload-artifact@v4
      with:
        name: LAUNCHER
        path: ${{env.LAUNCHER_BIN}}

  deploy-launcher:
    runs-on: ubuntu-latest
    needs: [build-launcher, create-release, sign-launcher]
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download LAUNCHER
      uses: actions/download-artifact@v4
      with:
        name: LAUNCHER
        path: ./
    - name: Upload Release Asset
      id: upload-release-asset-launcher
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ${{env.LAUNCHER_BIN}}
        asset_name: LAUNCHER.BIN
        asset_content_type: application/octet-stream

#-------------------------------------------------------------------------------

  # Flasher for the SLOT2 cartridge
  build-flasher:
    runs-on: ubuntu-latest
    container: 
      image: z88dk/z88dk

    steps:
    - uses: actions/checkout@v3
    - name: Build launcher application
      run: |
        cd src
        sed -i 's/node[[:digit:]]\+/node2000000/g' Makefile
        make flasher
        ls -alh FLASHER*
    - name: Upload flasher
      uses: actions/upload-artifact@v4
      with:
        name: FLASHER
        path: src/${{env.FLASHER_BIN}}

  deploy-flasher:
    runs-on: ubuntu-latest
    needs: [build-flasher, create-release]
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: FLASHER
        path: ./
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ${{env.FLASHER_BIN}}
        asset_name: FLASHER.BIN
        asset_content_type: application/octet-stream

################################################################################

  # Modified BASIC cartridge
  build-basic:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y python3 python3-numpy z80asm make
    - name: Build modified basic cartridge
      run: |
        cd basicmod
        z80asm bootstrap.asm -o bootstrap.bin
        z80asm launcher.asm -o launcher.bin
        python hackrom.py
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: BASICBOOTSTRAP
        path: basicmod/${{env.BASICROM_BIN}}

  deploy-basic-cartridge:
    runs-on: ubuntu-latest
    needs: [build-basic, create-release]
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: BASICBOOTSTRAP
        path: ./
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ${{env.BASICROM_BIN}}
        asset_name: BASICBOOTSTRAP.BIN
        asset_content_type: application/octet-stream
  
#-------------------------------------------------------------------------------

  # Multirom cartridges

  build-multirom-4x16k:
    runs-on: ubuntu-latest
    needs: [build-basic, build-flasher]
    steps:
    - name: Install dependencies
      run: sudo apt install -y wget
    - uses: actions/checkout@v3
    - name: Download modified BASIC rom
      uses: actions/download-artifact@v4
      with:
        name: BASICBOOTSTRAP
        path: ./
    - name: Download flasher
      uses: actions/download-artifact@v4
      with:
        name: FLASHER
        path: ./
    - name: Build modified basic cartridge
      run: |
        wget https://github.com/ifilot/p2000t-ram-expansion-board/releases/latest/download/RAMTEST.BIN
        truncate -s 16k ${{env.BASICROM_BIN}}
        truncate -s 16k ${{env.FLASHER_BIN}}
        cat ${{env.BASICROM_BIN}} ${{env.FLASHER_BIN}} RAMTEST.BIN basicmod/BASICROM.BIN > MULTIROM.BIN
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: MULTIROM-4x16k
        path: ${{env.MULTIROM_BIN}}

  build-multirom-32x16k:
    runs-on: ubuntu-latest
    needs: [build-basic, build-flasher]
    steps:
    - name: Install dependencies
      run: sudo apt install -y wget python3
    - uses: actions/checkout@v3
    - name: Download modified BASIC rom
      uses: actions/download-artifact@v4
      with:
        name: BASICBOOTSTRAP
        path: ./
    - name: Download flasher
      uses: actions/download-artifact@v4
      with:
        name: FLASHER
        path: ./
    - name: Build modified basic cartridge
      run: |
        wget https://github.com/ifilot/p2000t-ram-expansion-board/releases/latest/download/RAMTEST.BIN
        truncate -s 16k ${{env.BASICROM_BIN}}
        truncate -s 16k ${{env.FLASHER_BIN}}
        python3 roms/build_rom.py
        truncate -s 512k MULTIROM.BIN # resize to 512kb
        mv MULTIROM.BIN MULTIROM-32x16k.BIN
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: MULTIROM-32x16k
        path: MULTIROM-32x16k.BIN

  deploy-multirom-4x16k:
    runs-on: ubuntu-latest
    needs: [build-multirom-4x16k, build-multirom-32x16k, create-release]
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name:  MULTIROM-4x16k
        path: ./
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ${{env.MULTIROM_BIN}}
        asset_name: MULTIROM-4x16k.BIN
        asset_content_type: application/octet-stream

  deploy-multirom-32x16k:
    runs-on: ubuntu-latest
    needs: [build-multirom-4x16k, build-multirom-32x16k, create-release]
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name:  MULTIROM-32x16k
        path: ./
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: MULTIROM-32x16k.BIN
        asset_name: MULTIROM-32x16k.BIN
        asset_content_type: application/octet-stream

################################################################################

  build-card:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install -y python3 python3-pil
    - uses: actions/checkout@v3
    - name: Build card
      run: |
        python3 roms/card/card_creator.py
        mv card.png multirom-card.png
    - name: Upload card
      uses: actions/upload-artifact@v4
      with:
        name: multirom-card.png
        path: multirom-card.png

  deploy-card:
    runs-on: ubuntu-latest
    needs: [build-card, create-release]
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name:  multirom-card.png
        path: ./
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: multirom-card.png
        asset_name: multirom-card.png
        asset_content_type: image/png  

################################################################################

  # custom programs
  build-prg-helloworld:
    runs-on: ubuntu-latest
    container: 
      image: z88dk/z88dk

    steps:
    - uses: actions/checkout@v3
    - name: Build helloworld PRG
      run: |
        cd programs/helloworld
        sed -i 's/node[[:digit:]]\+/node2000000/g' Makefile
        make
        ls -alh
    - name: Upload HELLOWORLD.BIN
      uses: actions/upload-artifact@v4
      with:
        name: HELLOWORLD-UNSIGNED.PRG
        path: programs/helloworld/HELLOWORLD.PRG

  sign-prg-helloworld:
    runs-on: ubuntu-latest
    needs: [build-prg-helloworld]
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y python3
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: HELLOWORLD-UNSIGNED.PRG
        path: ./
    - name: Sign binary
      run: |
        python3 scripts/signprg.py HELLOWORLD.PRG
    - name: Upload HELLOWORLD.PRG
      uses: actions/upload-artifact@v4
      with:
        name: HELLOWORLD.PRG
        path: HELLOWORLD.PRG

#-------------------------------------------------------------------------------

  build-prg-moncrc16:
    runs-on: ubuntu-latest
    container: 
      image: z88dk/z88dk

    steps:
    - uses: actions/checkout@v3
    - name: Build CRC16 PRG
      run: |
        cd programs/crcmonitor
        sed -i 's/node[[:digit:]]\+/node2000000/g' Makefile
        make
        ls -alh
    - name: Upload MONCRC16.BIN
      uses: actions/upload-artifact@v4
      with:
        name: MONCRC16-UNSIGNED.PRG
        path: programs/crcmonitor/MONCRC16.PRG

  sign-prg-moncrc16:
    runs-on: ubuntu-latest
    needs: [build-prg-moncrc16]
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y python3
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: MONCRC16-UNSIGNED.PRG
        path: ./
    - name: Sign binary
      run: |
        python3 scripts/signprg.py MONCRC16.PRG
    - name: Upload MONCRC16.PRG
      uses: actions/upload-artifact@v4
      with:
        name: MONCRC16.PRG
        path: MONCRC16.PRG

#-------------------------------------------------------------------------------

  build-prg-casdump:
    runs-on: ubuntu-latest
    container: 
      image: z88dk/z88dk

    steps:
    - uses: actions/checkout@v3
    - name: Build CRC16 PRG
      run: |
        cd programs/casdump
        sed -i 's/node[[:digit:]]\+/node2000000/g' Makefile
        make cassettedump-prg
        mv -v CASDUMP.PRG CASDUMP.PRG
    - name: Upload CASDUMP.BIN
      uses: actions/upload-artifact@v4
      with:
        name: CASDUMP-UNSIGNED.PRG
        path: programs/casdump/CASDUMP.PRG

  sign-prg-casdump:
    runs-on: ubuntu-latest
    needs: [build-prg-casdump]
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y python3
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: CASDUMP-UNSIGNED.PRG
        path: ./
    - name: Sign binary
      run: |
        python3 scripts/signprg.py CASDUMP.PRG
    - name: Upload CASDUMP.PRG
      uses: actions/upload-artifact@v4
      with:
        name: CASDUMP.PRG
        path: CASDUMP.PRG

#-------------------------------------------------------------------------------

  packaging-programs:
    runs-on: ubuntu-latest
    needs: [sign-prg-helloworld, sign-prg-moncrc16]
    permissions: write-all
    steps:
    - name: Download MONCRC16
      uses: actions/download-artifact@v4
      with:
        name: MONCRC16.PRG
        path: ./
    - name: Download HELLOWORLD.PRG
      uses: actions/download-artifact@v4
      with:
        name: HELLOWORLD.PRG
        path: ./
    - name: Upload PROGRAMS.zip
      uses: actions/upload-artifact@v4
      with:
        name: PROGRAMS.zip
        path: |
          *.PRG

  deploy-programs:
    runs-on: ubuntu-latest
    needs: [packaging-programs, create-release]
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download program package
      uses: actions/download-artifact@v4
      with:
        name: PROGRAMS.zip
        path: ./
    - name: Repackage
      run: zip PROGRAMS.zip *.PRG
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: PROGRAMS.zip
        asset_name: PROGRAMS.zip
        asset_content_type: application/octet-stream
  
  deploy-casdump:
    runs-on: ubuntu-latest
    needs: [sign-prg-casdump, create-release]
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download CASDUMP.PRG
      uses: actions/download-artifact@v4
      with:
        name: CASDUMP.PRG
        path: ./
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: CASDUMP.PRG
        asset_name: CASDUMP.PRG
        asset_content_type: application/octet-stream